# These are supported funding model platforms

github: [tuanbagues, tuanbaguesteem]
patreon: tuanbagues
open_collective: tuanbagues
ko_fi: tuanbagues
tidelift: npm/tuanbagues
community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: tuanbagues
issuehunt: tuanbagues
lfx_crowdfunding: # Replace with a single LFX Crowdfunding project-name e.g., cloud-foundry
polar: tuanbagues
buy_me_a_coffee: @tuanbagues
thanks_dev: # Replace with a single thanks.dev username
custom:  ['https://www.paypal.com/paypalme/mmsicompany', 'tuanbagues.web.id']

